### PR TITLE
description and other optionals, update-or-add

### PR DESCRIPTION
**Pull request by kgbvax**

### CODE REVIEW

**Comment by kgbvax** [comment]
Sorry, wring repo

**Comment by narkisr** [comment]
Hey, just wondering why you guys don't push upstream, your not obligated to do so off course but id be more then happy to have a single successful project and not a bunch of forks

Thanks

**Comment by kgbvax** [comment]
That would make sense and reduce maintenance. \o/

Right now I am hacking something together for 32C3. As I also still learning clojure i don’t think I am ready yet.
Once we get this to work I’ll think about a way of upstreaming it (without breaking compatibility).

Cheers,

**Comment by narkisr** [comment]
Cool, what is 32C3?

**Comment by kgbvax** [comment]
https://en.wikipedia.org/wiki/Chaos_Communication_Congress https://en.wikipedia.org/wiki/Chaos_Communication_Congress
:-)

**Comment by narkisr** [comment]
Looks awesome id wish I could attend :)

**Pull request closed without merging**
